/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as AuthenticatedEditIdRouteImport } from "./routes/_authenticated/edit/$id";
import { Route as AuthenticatedHistoryRouteImport } from "./routes/_authenticated/history";
import { Route as AuthenticatedHomeRouteImport } from "./routes/_authenticated/home";
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated/settings";
import { Route as AuthenticatedSettingsIndexRouteImport } from "./routes/_authenticated/settings/index";
import { Route as AuthenticatedStatisticsRouteImport } from "./routes/_authenticated/statistics";
import { Route as AuthenticatedStatisticsMonthRouteImport } from "./routes/_authenticated/statistics/$month";
import { Route as AuthenticatedStatisticsIndexRouteImport } from "./routes/_authenticated/statistics/index";
import { Route as IndexRouteImport } from "./routes/index";

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: "/statistics",
  path: "/statistics",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedStatisticsIndexRoute =
  AuthenticatedStatisticsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedStatisticsRoute,
  } as any);
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedStatisticsMonthRoute =
  AuthenticatedStatisticsMonthRouteImport.update({
    id: "/$month",
    path: "/$month",
    getParentRoute: () => AuthenticatedStatisticsRoute,
  } as any);
const AuthenticatedEditIdRoute = AuthenticatedEditIdRouteImport.update({
  id: "/edit/$id",
  path: "/edit/$id",
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/history": typeof AuthenticatedHistoryRoute;
  "/home": typeof AuthenticatedHomeRoute;
  "/settings": typeof AuthenticatedSettingsRouteWithChildren;
  "/statistics": typeof AuthenticatedStatisticsRouteWithChildren;
  "/edit/$id": typeof AuthenticatedEditIdRoute;
  "/statistics/$month": typeof AuthenticatedStatisticsMonthRoute;
  "/settings/": typeof AuthenticatedSettingsIndexRoute;
  "/statistics/": typeof AuthenticatedStatisticsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/history": typeof AuthenticatedHistoryRoute;
  "/home": typeof AuthenticatedHomeRoute;
  "/edit/$id": typeof AuthenticatedEditIdRoute;
  "/statistics/$month": typeof AuthenticatedStatisticsMonthRoute;
  "/settings": typeof AuthenticatedSettingsIndexRoute;
  "/statistics": typeof AuthenticatedStatisticsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/_authenticated/history": typeof AuthenticatedHistoryRoute;
  "/_authenticated/home": typeof AuthenticatedHomeRoute;
  "/_authenticated/settings": typeof AuthenticatedSettingsRouteWithChildren;
  "/_authenticated/statistics": typeof AuthenticatedStatisticsRouteWithChildren;
  "/_authenticated/edit/$id": typeof AuthenticatedEditIdRoute;
  "/_authenticated/statistics/$month": typeof AuthenticatedStatisticsMonthRoute;
  "/_authenticated/settings/": typeof AuthenticatedSettingsIndexRoute;
  "/_authenticated/statistics/": typeof AuthenticatedStatisticsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/history"
    | "/home"
    | "/settings"
    | "/statistics"
    | "/edit/$id"
    | "/statistics/$month"
    | "/settings/"
    | "/statistics/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/history"
    | "/home"
    | "/edit/$id"
    | "/statistics/$month"
    | "/settings"
    | "/statistics";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/_authenticated/history"
    | "/_authenticated/home"
    | "/_authenticated/settings"
    | "/_authenticated/statistics"
    | "/_authenticated/edit/$id"
    | "/_authenticated/statistics/$month"
    | "/_authenticated/settings/"
    | "/_authenticated/statistics/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/statistics": {
      id: "/_authenticated/statistics";
      path: "/statistics";
      fullPath: "/statistics";
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/settings": {
      id: "/_authenticated/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/home": {
      id: "/_authenticated/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof AuthenticatedHomeRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/history": {
      id: "/_authenticated/history";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/statistics/": {
      id: "/_authenticated/statistics/";
      path: "/";
      fullPath: "/statistics/";
      preLoaderRoute: typeof AuthenticatedStatisticsIndexRouteImport;
      parentRoute: typeof AuthenticatedStatisticsRoute;
    };
    "/_authenticated/settings/": {
      id: "/_authenticated/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    "/_authenticated/statistics/$month": {
      id: "/_authenticated/statistics/$month";
      path: "/$month";
      fullPath: "/statistics/$month";
      preLoaderRoute: typeof AuthenticatedStatisticsMonthRouteImport;
      parentRoute: typeof AuthenticatedStatisticsRoute;
    };
    "/_authenticated/edit/$id": {
      id: "/_authenticated/edit/$id";
      path: "/edit/$id";
      fullPath: "/edit/$id";
      preLoaderRoute: typeof AuthenticatedEditIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute;
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
};

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren
  );

interface AuthenticatedStatisticsRouteChildren {
  AuthenticatedStatisticsMonthRoute: typeof AuthenticatedStatisticsMonthRoute;
  AuthenticatedStatisticsIndexRoute: typeof AuthenticatedStatisticsIndexRoute;
}

const AuthenticatedStatisticsRouteChildren: AuthenticatedStatisticsRouteChildren =
  {
    AuthenticatedStatisticsMonthRoute: AuthenticatedStatisticsMonthRoute,
    AuthenticatedStatisticsIndexRoute: AuthenticatedStatisticsIndexRoute,
  };

const AuthenticatedStatisticsRouteWithChildren =
  AuthenticatedStatisticsRoute._addFileChildren(
    AuthenticatedStatisticsRouteChildren
  );

interface AuthenticatedRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute;
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute;
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren;
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRouteWithChildren;
  AuthenticatedEditIdRoute: typeof AuthenticatedEditIdRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRouteWithChildren,
  AuthenticatedEditIdRoute: AuthenticatedEditIdRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
