import { clientsClaim, skipWaiting } from "workbox-core";
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { NetworkFirst } from "workbox-strategies";

declare let self: ServiceWorkerGlobalScope & { __WB_MANIFEST: any };

skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

// Precache all assets generated by your build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache Supabase API calls with NetworkFirst strategy
registerRoute(
  ({ url }) => url.origin.includes("supabase.co"),
  new NetworkFirst({
    cacheName: "supabase-api-cache",
  })
);
