import { clientsClaim, skipWaiting } from "workbox-core";
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";

type PrecacheManifestEntry =
  | string
  | {
      url: string;
      revision?: string | null;
      integrity?: string;
    };

declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: PrecacheManifestEntry[];
};

skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

// Precache all assets generated by your build process
precacheAndRoute(self.__WB_MANIFEST);
